### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by guptar1** [YannickRe/spfx-msgraph-peoplesearch#4]
I keep getting this error after installing m365 CLI

![Capture](https://user-images.githubusercontent.com/72985323/98239034-3d8df600-1f5f-11eb-858d-67958b61ed93.PNG)

**Comment by YannickRe** [comment]
You better leave that as a bug on their repository: https://github.com/pnp/cli-microsoft365/

One thing you could try tho, is to use the complete commands:
`m365 login`
followed by
`m365 spo serviceprincipal grant add --resource 'Microsoft Graph' --scope 'User.Read.All'`

The interactive mode is no longer available since they moved from Office 365 CLI to CLI for Microsoft 365

**Comment by guptar1** [comment]
Thanks @YannickRe  for your response. Unfortunately no command are working. I keep getting the same error. Is there a way to grant this permission using powershell or manually?

**Comment by YannickRe** [comment]
@guptar1 You can do the same by using [PnP PowerShell(https://github.com/pnp/PnP-PowerShell), with [Grant-PnPTenantServicePrincipalPermission(https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/grant-pnptenantserviceprincipalpermission?view=sharepoint-ps)

In that case, you'd use
```
Grant-PnPTenantServicePrincipalPermission -Scope "User.Read.All" -Resource "Microsoft Graph"
```

I hope this helps you be succesful!

**Comment by YannickRe** [comment]
@guptar1 Has this been resolved for you? Can I close the issue?

**Comment by guptar1** [comment]
Yes please close. Thanks for your help
