### ISSUE TITLE
People Search Results: Adaptive Cards not hoverable/clickable anymore

### ISSUE THREAD

**Issue by AZNak** [YannickRe/spfx-msgraph-peoplesearch#61]
When searching and getting people results, there was the functionality to hover over the found user or click on the found user to get more details and open the People Card.
That does not work anymore since this week.

**Comment by YannickRe** [comment]
Thank you for reporting, I got the same information through other routes as well. I checked, and can confirm it is broken at the moment. This was always a finicky feature since it was never officially supported by Microsoft to use the Live Persona Card in a 3rd party solution.

It's super busy at the moment, so it will be a while until I can look into it unfortunately.

**Comment by GhostriderC6** [comment]
Same issue here :( 
But thank you for your support!!!

**Comment by YannickRe** [comment]
PnP had the same issue: https://github.com/pnp/sp-dev-fx-controls-react/issues/1241
Their great work made it an easy fix for me, so I have put out a new release: https://github.com/YannickRe/spfx-msgraph-peoplesearch/releases/tag/v2.7.1
